env:
  global:
  - REVIEWDOG_VERSION="0.9.10"
  - secure: YXQdS4QeQolOVXwo05hIoaLaGHnSYCi0V4n0NiYJnZfbhEGX+4Nt8iMjznIY6zwNcRSH+GkYVWZx8c+SpOiPtbX7omdOo5ZGN5jxGLd2p3oDmOkF7KjBuZIbpEsZHqZM+I7OKxPNlhV1rk0FgyFCmn6CCU33CUwJQCIask1lNCh+ZdEjeubJFb+6Tc1UIBTOh7vFg+6kwlXwn3XsYAg0gwipXRZ+cWl/jssJOgMzsCY4t98kWCG23hvBiSUyov6y1fslO1vuiyfoep3837s0JbWRSHYvMBqqQe/VLZjM/ySoGPmjcyO3Ex1Ujgl0guw+PABmU5y7nZ3RClX40QEE49e3MhnwPI3dYST5ubCgnTcqk5eZRWa/bP27ARAmYcXmxIreasGWpTNUJrSC45r39gAMkiePUnypawHrTvC1MOnMD4GG7K2KwNnQ9wQ5dG67Jwsjk8kYp+aCXqqFVe4aaPj2nptyfbLjVcODF/vL4hDu9PW35GXGX5e96BcgRaVWpdLmYwkW2wPtaevwHBkb1/acC4uheP9sC/dRJbyRTme5/ccQHXJSstU5g/xkottvq5VRaXKJYsUhWng40PlDFE5IcF/1h5WBMVUZpDgFIRZ04yKqZZmr13gl55SBK/y0wrrVD4lgbTWSswXH3Ie4JKgNJopAjndlVgLCLFqiaOg=

language: node_js
node_js: lts/*

script:
- bash .travis/prevent-base-master.sh
- bash .travis/omit-dist.sh
- npm run lint
- npm run build

after_failure:
- bash .travis/review.sh
